name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Dist
        uses: actions/checkout@v2
        with:
          repository: 'wdvxdr1123/dist'
          ref: master
          ssh-key: ${{ secrets.SSH_KEY }}
          path: upstream/dist

      - name: Update Dist
        run: |
          cp -f dist/*.tar.gz upstream/dist/
          cp -f dist/*.zip upstream/dist/
          cd upstream/dist
          git config --local user.name 'Github Actions'
          git config --local user.email 'github-actions@users.noreply.github.com'
          git add --all
          git commit -m "update to ${GITHUB_REF#"refs/tags/"}"
          git tag -a ${GITHUB_REF#"refs/tags/"}
          git push
          git push --tags
